### ISSUE TITLE
Fails to build on windows (path issues/assumptions?)

### ISSUE THREAD

**Issue by jChapman** [onmax/astro-single-file#2]
After adding html-minifier-terser (see #1) I ran into an issue when trying to run the build command. I believe this is because I'm on Windows and there's some assumption about the path style 

```
> astro build

09:00:30 PM [build] output target: static
09:00:30 PM [build] Collecting build info...
09:00:30 PM [build] Completed in 13ms.
09:00:30 PM [build] Building static entrypoints...
09:00:32 PM [build] Completed in 2.10s.

 generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+11ms)
Completed in 17ms.

 error   ENOENT: no such file or directory, scandir '/D:/dev/testSinglePage/dist/'
Error: ENOENT: no such file or directory, scandir '/D:/dev/testSinglePage/dist/'
    at Module.readdirSync (node:fs:1405:3)
    at Object.astro:build:done (file:///D:/dev/testSinglePage/node_modules/astro-single-file/index.js:9:34)
    at runHookBuildDone (file:///D:/dev/testSinglePage/node_modules/astro/dist/integrations/index.js:268:58)
    at AstroBuilder.build (file:///D:/dev/testSinglePage/node_modules/astro/dist/core/build/index.js:109:11)
    at async AstroBuilder.run (file:///D:/dev/testSinglePage/node_modules/astro/dist/core/build/index.js:128:7)
    at async build (file:///D:/dev/testSinglePage/node_modules/astro/dist/core/build/index.js:22:3)
    at async runCommand (file:///D:/dev/testSinglePage/node_modules/astro/dist/cli/index.js:189:14)
    at async cli (file:///D:/dev/testSinglePage/node_modules/astro/dist/cli/index.js:206:5)
```

**Comment by onmax** [comment]
Fixed: using node:path.join for cross-platform path handling
